# Site settings
title: Portfolio
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rahul Menon
user_description: I am looking for opportunities where I can improve my current skills, learn new useful skills, and use Data Science and Machine Learning to solve interesting and meaningful problems.
#user_title: Software Developer
email: rmenon1998@gmail.com
#twitter_username: lorem_ipsum
github_username:  phenomenon98
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
