# Site settings
title: Portfolio
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rahul Menon
user_description: I am an avid technology enthusiast with a passion for using Data Science and Machine Learning to solve interesting and meaningful problems.
email: rmenon1998@gmail.com
#twitter_username: lorem_ipsum
github_username:  https://github.com/phenomenon98
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
